application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "postgres"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"  